include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true

linter:
  rules:
    - prefer_final_locals
    - prefer_relative_imports
    # https://github.com/dart-lang/lints#migrating-from-packagepedantic
    - always_declare_return_types
    - prefer_single_quotes
    - unawaited_futures
    - unsafe_html
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables